//
// Created by drhaz on 29.06.2026.
//

#ifndef SMB_SYTYPES_HPP
#define SMB_SYTYPES_HPP

namespace engine::systems {
    enum class SYInputAction {
                MoveForward,
                MoveBackward,
                MoveLeft,
                MoveRight,
                MoveUp,
                MoveDown,
                Jump,
                Crouch,
                Sprint,
                Interact,
                Interact2,
                RotateLeft,
                RotateRight,
                LookUp,
                LookDown,
                LookLeft,
                LookRight,
                CameraMoveForward,
                CameraMoveBackward,
                CameraMoveLeft,
                CameraMoveRight,
                CameraMoveUp,
                Reset,
                Quit
        };

        enum class SYKey {
                A,
                B,
                C,
                D,
                E,
                F,
                G,
                H,
                I,
                J,
                K,
                L,
                M,
                N,
                O,
                P,
                Q,
                R,
                S,
                T,
                U,
                V,
                W,
                X,
                Y,
                Z,
                One,
                Two,
                Three,
                Four,
                Five,
                Six,
                Seven,
                Eight,
                Nine,
                Zero,
                Space,
                Escape,
                Enter,
                Backspace,
                Tab,
                Shift,
                Control,
                Alt,
                Left,
                Right,
                Up,
                Down,
                PageUp,
                PageDown,
                Home,
                End,
                Insert,
                Delete,
                F1,
                F2,
                F3,
                F4,
                F5,
                F6,
                F7,
                F8,
                F9,
                F10,
                F11,
                F12,
                NumPad0,
                NumPad1,
                NumPad2,
                NumPad3,
                NumPad4,
                NumPad5,
                NumPad6,
                NumPad7,
                NumPad8,
                NumPad9,
                NumPadAdd,
                NumPadSubtract,
                NumPadMultiply,
                NumPadDivide,
                NumPadDecimal,
                NumPadEnter,
                NumPadEqual,
                NumPadComma,
                NumPadMinus,
                NumPadPeriod,
                NumPadSlash,
                NumPadLeftBracket,
                NumPadRightBracket,
                NumPadBackslash,
                NumPadSemicolon,
                NumPadApostrophe,
                NumPadGrave,
                NumLock,
                CapsLock,
                Minus,
                Equal,
                LeftBracket,
                RightBracket,
                Backslash,
                Semicolon,
                Apostrophe,
                Grave,
                Comma,
                Period,
                Slash,
                Return,
        };

        enum class SYMouseButton {
                Left,
                Middle,
                Right,
                X1,
                X2,
            };

        struct SYMouseState {
                float x{0.0f};
                float y{0.0f};

                float deltaX{0.0f};
                float deltaY{0.0f};

                float wheelX{0.0f};
                float wheelY{0.0f};
        };
}

#endif //SMB_SYTYPES_HPP
